# Generated by Django 6.0.6 on 2026-06-12 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('charging', '0001_initial'),
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_type', models.CharField(default='hardware', max_length=32)),
                ('fault_status', models.CharField(default='open', max_length=16)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('recovered_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('pile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fault_records', to='station.chargingpile')),
            ],
            options={
                'db_table': 'operations_fault_record',
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(max_length=32)),
                ('target_type', models.CharField(max_length=32)),
                ('target_id', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to='accounts.adminaccount')),
            ],
            options={
                'db_table': 'operations_operation_log',
            },
        ),
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(max_length=16)),
                ('report_date', models.DateField()),
                ('total_charge_num', models.IntegerField(default=0)),
                ('total_charge_time', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_charge_capacity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_charge_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('pile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_snapshots', to='station.chargingpile')),
            ],
            options={
                'db_table': 'operations_report_snapshot',
            },
        ),
        migrations.CreateModel(
            name='RescheduleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_type', models.CharField(max_length=32)),
                ('result_status', models.CharField(default='success', max_length=32)),
                ('handled_at', models.DateTimeField(auto_now_add=True)),
                ('fault_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedules', to='operations.faultrecord')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedules', to='charging.chargingrequest')),
                ('source_pile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedule_sources', to='station.chargingpile')),
                ('target_pile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedule_targets', to='station.chargingpile')),
            ],
            options={
                'db_table': 'operations_reschedule_record',
            },
        ),
    ]
