# Generated by Django 6.0.6 on 2026-06-12 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('charging', '0001_initial'),
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=64)),
                ('service_price', models.DecimalField(decimal_places=2, default=0.8, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'billing_tariff_policy',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=32, unique=True)),
                ('bill_date', models.DateField()),
                ('total_charge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_charge_duration', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('total_charge_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pay_status', models.CharField(default='unpaid', max_length=16)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='accounts.useraccount')),
            ],
            options={
                'db_table': 'billing_bill',
            },
        ),
        migrations.CreateModel(
            name='TariffPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(max_length=16)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='billing.tariffpolicy')),
            ],
            options={
                'db_table': 'billing_tariff_period',
            },
        ),
        migrations.CreateModel(
            name='ChargeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_no', models.CharField(max_length=32, unique=True)),
                ('charge_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charge_duration', models.DecimalField(decimal_places=4, max_digits=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('charge_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details', to='billing.bill')),
                ('pile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_details', to='station.chargingpile')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_details', to='charging.chargingrequest')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charge_detail', to='charging.chargingsession')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_details', to='accounts.vehicle')),
                ('tariff_policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.tariffpolicy')),
            ],
            options={
                'db_table': 'billing_charge_detail',
            },
        ),
    ]
