# Generated by Django 6.0.6 on 2026-06-12 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station_code', models.CharField(max_length=32, unique=True)),
                ('station_name', models.CharField(max_length=128)),
                ('status', models.CharField(default='active', max_length=20)),
            ],
            options={
                'db_table': 'station_charging_station',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fast_pile_num', models.IntegerField(default=2)),
                ('slow_pile_num', models.IntegerField(default=3)),
                ('waiting_area_size', models.IntegerField(default=10)),
                ('charging_queue_len', models.IntegerField(default=5)),
                ('fault_strategy', models.CharField(default='priority', max_length=20)),
                ('dispatch_mode', models.CharField(default='normal', max_length=20)),
                ('service_price', models.DecimalField(decimal_places=2, default=0.8, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateTimeField(auto_now_add=True)),
                ('fast_queue_seq', models.IntegerField(default=0)),
                ('slow_queue_seq', models.IntegerField(default=0)),
                ('waiting_dispatch_paused', models.BooleanField(default=False)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='station.chargingstation')),
            ],
            options={
                'db_table': 'station_system_config',
            },
        ),
        migrations.CreateModel(
            name='ChargingPile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pile_no', models.CharField(max_length=32)),
                ('pile_type', models.CharField(max_length=1)),
                ('rated_power', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(default='off', max_length=20)),
                ('is_enabled', models.BooleanField(default=False)),
                ('current_queue_length', models.IntegerField(default=0)),
                ('total_charge_num', models.IntegerField(default=0)),
                ('total_charge_time', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_charge_capacity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piles', to='station.chargingstation')),
            ],
            options={
                'db_table': 'station_charging_pile',
                'unique_together': {('station', 'pile_no')},
            },
        ),
    ]
