# Generated by Django 6.0.6 on 2026-06-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationClock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('current_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'station_simulation_clock',
            },
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='charging_queue_len',
            field=models.IntegerField(default=3),
        ),
    ]
