# Generated by Django 6.0.6 on 2026-06-12 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_no', models.CharField(max_length=32, unique=True)),
                ('request_mode', models.CharField(max_length=1)),
                ('request_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='queuing', max_length=32)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('charge_started_at', models.DateTimeField(blank=True, null=True)),
                ('charge_ended_at', models.DateTimeField(blank=True, null=True)),
                ('queue_num', models.CharField(blank=True, default='', max_length=16)),
                ('remark', models.TextField(blank=True, default='')),
                ('current_pile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_requests', to='station.chargingpile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_requests', to='accounts.useraccount')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_requests', to='accounts.vehicle')),
            ],
            options={
                'db_table': 'charging_request',
            },
        ),
        migrations.CreateModel(
            name='ChargingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_no', models.CharField(max_length=32, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('charged_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('charged_duration', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('session_status', models.CharField(default='active', max_length=20)),
                ('stop_reason', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_sessions', to='station.chargingpile')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='charging.chargingrequest')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_sessions', to='accounts.vehicle')),
            ],
            options={
                'db_table': 'charging_session',
            },
        ),
        migrations.CreateModel(
            name='DispatchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=32)),
                ('dispatch_strategy', models.CharField(blank=True, default='', max_length=32)),
                ('before_status', models.CharField(max_length=32)),
                ('after_status', models.CharField(max_length=32)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('operator_type', models.CharField(default='system', max_length=16)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_records', to='charging.chargingrequest')),
                ('target_pile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='station.chargingpile')),
            ],
            options={
                'db_table': 'charging_dispatch_record',
            },
        ),
        migrations.CreateModel(
            name='QueueTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_num', models.CharField(max_length=16)),
                ('queue_type', models.CharField(max_length=20)),
                ('queue_position', models.IntegerField(default=0)),
                ('entered_queue_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_tickets', to='station.chargingpile')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_tickets', to='charging.chargingrequest')),
            ],
            options={
                'db_table': 'charging_queue_ticket',
                'ordering': ['queue_position', 'entered_queue_at'],
            },
        ),
    ]
